/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: "jsdom",
  roots: ["<rootDir>/tests"],
  testMatch: [
    "<rootDir>/tests/ts/AuditTrailViewer.test.tsx",
    "<rootDir>/tests/ts/vipShowcase.test.ts",
    "<rootDir>/tests/ts/sepExecution.test.ts",
    "<rootDir>/tests/ts/sepExecutionDashboard.test.tsx",
    "<rootDir>/tests/ts/planPackaging.test.ts",
    "<rootDir>/tests/ts/onboardingGuide.test.ts",
    "<rootDir>/tests/ts/SetupWizard.test.tsx",
    "<rootDir>/tests/ts/reportLenses.test.ts",
    "<rootDir>/tests/ts/trustledgerDomain.test.ts",
    "<rootDir>/tests/ts/trustOverlay.test.ts",
    "<rootDir>/tests/ts/engagementOverlayStore.test.ts",
    "<rootDir>/tests/ts/trustLayer.test.ts",
    "<rootDir>/tests/ts/trustAnalytics.test.ts",
    "<rootDir>/tests/ts/ReportsHub.test.tsx",
    "<rootDir>/tests/ts/trustIntelligence.test.ts",
    "<rootDir>/tests/ts/trustGlobalSouth.test.tsx",
    "<rootDir>/tests/ts/trustMvpReadiness.test.ts",
    "<rootDir>/tests/ts/trustWorkspace.test.tsx",
    "<rootDir>/tests/ts/trustCloud.test.ts",
    "<rootDir>/tests/ts/trustEngagementApply.test.ts",
    "<rootDir>/tests/ts/trustParticipationQuality.test.ts",
    "<rootDir>/tests/ts/trustClaimVerification.test.ts",
    "<rootDir>/tests/ts/dashboardOverview.test.ts",
    "<rootDir>/tests/ts/dashboardOverviewUi.test.tsx",
  ],
  setupFilesAfterEnv: ["<rootDir>/tests/jest.setup.ts"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^server-only$": "<rootDir>/tests/empty.js",
  },
  transform: {
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        tsconfig: {
          module: "commonjs",
          moduleResolution: "node",
          esModuleInterop: true,
          strict: true,
          skipLibCheck: true,
          isolatedModules: true,
          jsx: "react-jsx",
          types: ["jest", "node"],
          target: "ES2020",
        },
      },
    ],
  },
  moduleFileExtensions: ["ts", "tsx", "js", "json"],
};
